In [46]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [47]:
import numpy as np
import pandas as pd

In [48]:
data = pd.read_csv('/content/spam.csv')

In [49]:
data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [50]:
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [51]:
data.tail()

     Category                                            Message
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

In [52]:
data = pd.read_csv('/content/spam.csv')

In [53]:
data.columns = ["label","messages"]

In [54]:
data

     label                                           messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x = data['messages']
y = data['label']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [57]:
x_train

5279    Helloooo... Wake up..! "Sweet" "morning" "welc...
1008    I don't quite know what to do. I still can't g...
907     all the lastest from Stereophonics, Marley, Di...
1485                               Sorry, I'll call later
4004    somewhere out there beneath the pale moon ligh...
                              ...
2604    Im at arestaurant eating squid! i will be out ...
4994    HEY KATE, HOPE UR OK... WILL GIVE U A BUZ WEDL...
4487                                 have * good weekend.
2935      Yup n her fren lor. I'm meeting my fren at 730.
3436    Hi darlin i cantdo anythingtomorrow as myparen...
Name: messages, Length: 4457, dtype: object

In [58]:
y_train

5279     ham
1008     ham
907     spam
1485     ham
4004     ham
        ...
2604     ham
4994     ham
4487     ham
2935     ham
3436     ham
Name: label, Length: 4457, dtype: object

In [59]:
x_train.count()
y_train.count()

np.int64(4457)

In [60]:
print(x_train.count() == y_train.count())

True

In [61]:
x_test

5037    You won't believe it but it's true. It's Incre...
1646                      I.ll post her out l8r. In class
1077         Where can download clear movies. Dvd copies.
2348                       But i dint slept in afternoon.
1980                   Shhhhh nobody is supposed to know!
                              ...
1943       K...k:)why cant you come here and search job:)
1169    Ok . . now i am in bus. . If i come soon i wil...
2709                              Nah, I'm a perpetual DD
4102    GSOH? Good with SPAM the ladies?U could b a ma...
613                                I have many dependents
Name: messages, Length: 1115, dtype: object

In [62]:
y_test

5037    spam
1646     ham
1077     ham
2348     ham
1980     ham
        ...
1943     ham
1169     ham
2709     ham
4102    spam
613      ham
Name: label, Length: 1115, dtype: object

In [63]:
x_test.count()
y_test.count()

np.int64(1115)

In [64]:
print(x_test.count() == y_test.count())

True

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [66]:
vector = TfidfVectorizer()
x_trainv = vector.fit_transform(x_train)
x_testv = vector.transform(x_test)

In [67]:
model = DecisionTreeClassifier()
model.fit(x_trainv,y_train)

DecisionTreeClassifier()

In [68]:
y_pred = model.predict(x_testv)
print(y_pred)

['spam' 'ham' 'ham' ... 'ham' 'spam' 'ham']

In [69]:
print(accuracy_score(y_test,y_pred))

0.9641255605381166

In [74]:
user_email = input ("Enter email text:")
user_v = vector.transform([user_email])
user_pred = model.predict(user_v)
print(user_pred)

Enter email text:freee freee freee
['ham']